server:
  port: ${metraoffer-ui-port:8074}

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
      
logging.level.com.ericsson: DEBUG
logging.level.com.ericsson.ecb: DEBUG
